"""
Django settings for digital_wallet project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-3pn^9m2v&&nmzk5uf_hc4g__dy5gy5=jsxojm-xdma$2qszcmd",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = (
    config("DJANGO_ALLOWED_HOSTS", default="", cast=str).split(",")
    if config("DJANGO_ALLOWED_HOSTS", default="", cast=str)
    else []
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "phonenumber_field",
    "django_filters",
    "drf_spectacular",
    # local apps
    "users",
    "transactions",
    "wallets",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "shared.middlewares.sliding_access_token_middleware.SlidingAccessTokenMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "digital_wallet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "digital_wallet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _database_from_env():
    if config("DB_HOST", default="", cast=str):
        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": config("DB_NAME", default="digital_wallet"),
                "USER": config("DB_USER", default="digital_wallet"),
                "PASSWORD": config("DB_PASSWORD", default="digital_wallet"),
                "HOST": config("DB_HOST", default="localhost"),
                "PORT": config("DB_PORT", default="5432"),
            }
        }

    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DATABASES = _database_from_env()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", "English"),
    ("ar", "Arabic"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "shared.auth.authentication.VersionedJWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_RATES": {
        "user": "30/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "shared.exceptions.api_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Digital Wallet API",
    "DESCRIPTION": (
        "API for user registration, wallet creation, deposits, internal transfers, "
        "and P2P flows. Uses short-lived JWT access tokens with rolling access "
        "rotation via the X-Access-Token response header. Wallets are referenced "
        "by public reference_tag values (e.g., @wlt_x7k9f.1) instead of internal IDs."
    ),
    "VERSION": "1.0.0",
    "SECURITY": [{"VersionedJWTAuthentication": []}],
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "COMPONENT_SPLIT_REQUEST": True,
    "AUTHENTICATION_EXTENSIONS": [
        "shared.auth.spectacular.VersionedJWTAuthenticationExtension",
    ],
}

# I added this for wallet security as tif token not used for more than 2 min it automatically expires
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}


AUTH_USER_MODEL = "users.User"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        # Django internal logs
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Your apps (explicit is better than implicit)
        "users": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "wallets": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "transactions": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "shared": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


WALLET_LIMITS = {
    "DEFAULT": {
        "MAX_PER_TRANSACTION": Decimal("5000.00"),
        "DAILY_WALLET_OUTGOING_LIMIT": Decimal("20000.00"),
    },
    # Optional per type overrides
    "P2P": {
        "MAX_PER_TRANSACTION": Decimal("2000.00"),
        "DAILY_WALLET_OUTGOING_LIMIT": Decimal("20000.00"),
    },
    "INTERNAL": {
        "MAX_PER_TRANSACTION": Decimal("10000.00"),
        "DAILY_WALLET_OUTGOING_LIMIT": Decimal("20000.00"),
    },
    "DEPOSIT": {
        "MAX_PER_TRANSACTION": Decimal("20000.00"),
    },
}
