# Generated by Django 6.0.1 on 2026-01-08 09:13

import django.core.validators
import django.db.models.deletion
import transactions.utils
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=transactions.utils.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("internal", "Internal transfer"),
                            ("p2p", "Peer to peer"),
                        ],
                        max_length=20,
                        verbose_name="Transaction type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "external_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Used for deposits (e.g., bank, card, cash, promo).",
                        max_length=50,
                        verbose_name="External source",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra transaction details (optional).",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "is_hold",
                    models.BooleanField(
                        default=False,
                        help_text="True if amount is reserved until approval (P2P pending).",
                        verbose_name="Is hold",
                    ),
                ),
                (
                    "held_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Held at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When transaction moved from pending to completed/rejected.",
                        null=True,
                        verbose_name="Resolved at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="wallets.wallet",
                        verbose_name="From wallet",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="wallets.wallet",
                        verbose_name="To wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "indexes": [
                    models.Index(
                        fields=["from_wallet", "-created_at"],
                        name="transaction_from_wa_e91953_idx",
                    ),
                    models.Index(
                        fields=["to_wallet", "-created_at"],
                        name="transaction_to_wall_c0223f_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="tx_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tx_type", "deposit"), _negated=True),
                            ("to_wallet__isnull", False),
                            _connector="OR",
                        ),
                        name="deposit_requires_to_wallet",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tx_type", "internal"), _negated=True),
                            models.Q(
                                ("from_wallet__isnull", False),
                                ("to_wallet__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="internal_requires_both_wallets",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tx_type", "p2p"), _negated=True),
                            models.Q(
                                ("from_wallet__isnull", False),
                                ("to_wallet__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="p2p_requires_both_wallets",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_hold", False), ("status", "pending"), _connector="OR"
                        ),
                        name="hold_must_be_pending",
                    ),
                ],
            },
        ),
    ]
