# Generated by Django 6.0.1 on 2026-01-08 07:18

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("savings", "Savings"),
                            ("travel", "Travel"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        default="current",
                        max_length=20,
                        verbose_name="Wallet type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique wallet name per user (e.g., My Savings, Travel Fund).",
                        max_length=100,
                        verbose_name="Wallet name",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "held_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "indexes": [
                    models.Index(
                        fields=["user", "wallet_type"],
                        name="wallets_wal_user_id_4eabbe_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="wallets_wal_user_id_935fe2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("user"),
                        name="uniq_wallet_name_per_user_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="wallet_balance_non_negative",
                    ),
                ],
            },
        ),
    ]
